# Generated by Django 2.0.13 on 2019-03-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='lastname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
